#!/bin/bash
_working_directory  3-listfiles      5-listfilesdigitonly  7-movethatfile  README.md
2-bring_me_home              4-listmorefiles  6-firstdirectory      l-listit        tmp
root@098510879ea8:/alx-system_engineering-devops/0x00-shell_basics# cat 1-listit
